### ISSUE TITLE
TypingTest returns wrong value for top

### ISSUE THREAD

**Issue by GioSDA** [AeroAstroid/TheBrainOfTWOWCentral#6]
When doing the command "tc/tt top" it returns the wrong value. I believe this to be because on line 82 it is requesting the value at index 0 without previously sorting the array, however I may be incorrect.

**Comment by Purplegaze** [comment]
The top command isn't currently finished and isn't supposed to be used. It was only returning something random I set it to when testing. It's not referenced anywhere in the help for tc/tt, so it shouldn't be used yet
